name: CI
on:
  pull_request:
    branches:
      - 'v3.11.x'
  push:
    branches:
      - 'v3.11.x'
jobs:
  build-test:
    name: Build and test on Erlang/OTP 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.13.4
      - run: make
      - run: make tests
